name: Build and Push

on:
  push:
    branches:
      - test1
      - test2
      - test3
      - test4
      - build
jobs:
  build-and-push:
    runs-on: self-hosted
    timeout-minutes: 300
    steps:
    - uses: actions/checkout@v1    
    - name: Build
      run: |
        docker build -t test:${GITHUB_SHA} .
