name: Build and Push

on:
  push:
    branches:
      - test1
      - test2
      - test3
      - test4
      - test5
      - test6
      - test7
      - test8
      - test9
      - build
jobs:
  build-and-push:
    runs-on: self-hosted
    timeout-minutes: 300
    steps:
    - uses: actions/checkout@v1    
    - name: Build
      env:
        DOCKER_HOST: "ssh://owner@172.17.0.1"
      run: |
        docker build -t test:${GITHUB_SHA} .
